<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="TestSUitesPermisos" time="74" tests="0" failures="0" errors="4">
   <testsuite name="TestSUitesPermisos" tests="0" failures="0" errors="4" time="74" timestamp="2018-12-24 13:17:22" hostname="jmatamoros - DESK-DEV01.BMinc.eu" id="Test Suites/TestSUitesPermisos">
      <properties>
         <property name="deviceName" value=""/>
         <property name="devicePlatform" value=""/>
         <property name="logFolder" value="C:\\Users\\jmatamoros.BMINC\\git\\katalonTest\\Reports\\TestSUitesPermisos\\20181224_131720"/>
         <property name="logFiles" value="C:\\Users\\jmatamoros.BMINC\\git\\katalonTest\\Reports\\TestSUitesPermisos\\20181224_131720\\execution0.log"/>
         <property name="attachments" value=""/>
         <property name="hostName" value="jmatamoros - DESK-DEV01.BMinc.eu"/>
         <property name="os" value="Windows 10 64bit"/>
         <property name="katalonVersion" value="5.10.0.1"/>
         <property name="browser" value="Chrome 71.0.3578.98"/>
         <property name="hostAddress" value="10.0.89.112"/>
         <property name="sessionId" value="1117a2dff3e82467c282db72ea3dc9a7"/>
         <property name="seleniumVersion" value="3.7.1"/>
         <property name="proxyInformation" value="ProxyInformation{proxyOption=NO_PROXY, proxyServerType=HTTP, password=, proxyServerAddress=, proxyServerPort=0}"/>
         <property name="platform" value="Windows 10"/>
      </properties>
      <testcase name="Test Cases/PREGAME/Permisos/PermisosCasino" classname="Test Cases/PREGAME/Permisos/PermisosCasino" status="ERROR">
         <error type="ERROR" message="Test Cases/PREGAME/Permisos/PermisosCasino FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosCasino.run(PermisosCasino:102)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545429055765.run(Script1545429055765.groovy:102)
	... 13 more
"/>
         <system-out><![CDATA[2018-12-24 13:17:22 - [TEST_CASE][ERROR] - Test Cases/PREGAME/Permisos/PermisosCasino: Test Cases/PREGAME/Permisos/PermisosCasino FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosCasino.run(PermisosCasino:102)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545429055765.run(Script1545429055765.groovy:102)
	... 13 more


2018-12-24 13:17:22 - [TEST_STEP][PASSED] - log = new com.kms.katalon.core.logging.KeywordLogger(): null

2018-12-24 13:17:22 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.loadFileInputStream(permisosExcelRuta): com.utils.ExcelsUtils.loadFileInputStream is PASSED

2018-12-24 13:17:23 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.loadFileInputStream is PASSED

2018-12-24 13:17:23 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.createReadXSSFWorkbook(): com.utils.ExcelsUtils.createReadXSSFWorkbook is PASSED

2018-12-24 13:17:23 - [MESSAGE][INFO] - input file create  Read java.io.FileInputStream@548e76f1

2018-12-24 13:17:23 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.createReadXSSFWorkbook is PASSED

2018-12-24 13:17:23 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.loadXSSFSheet("Casino"): com.utils.ExcelsUtils.loadXSSFSheet is PASSED

2018-12-24 13:17:23 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.loadXSSFSheet is PASSED

2018-12-24 13:17:23 - [TEST_STEP][PASSED] - url = com.utils.ExcelsUtils.getColumValue(1, 1): com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:17:23 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:17:23 - [TEST_STEP][PASSED] - userName = com.utils.ExcelsUtils.getColumValue(1, 2): com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:17:23 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:17:23 - [TEST_STEP][PASSED] - userPassword = com.utils.ExcelsUtils.getColumValue(1, 3): com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:17:23 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:17:23 - [TEST_STEP][PASSED] - startHour = com.utils.DateUtil.getHours(): com.utils.DateUtil.getHours is PASSED

2018-12-24 13:17:23 - [MESSAGE][PASSED] - com.utils.DateUtil.getHours is PASSED

2018-12-24 13:17:23 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 4, com.utils.DateUtil.getDate()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:23 - [MESSAGE][PASSED] - com.utils.DateUtil.getDate is PASSED

2018-12-24 13:17:23 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:23 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 5, startHour): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:23 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:23 - [TEST_STEP][PASSED] - try: com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:23 - [TEST_STEP][PASSED] - if (!(usuarioLogeado)): null

2018-12-24 13:17:23 - [TEST_STEP][PASSED] - callTestCase(findTestCase("PREGAME/SportBook/Login_Successfull"), ["url":url, "loginUser":userName, "loginPassword":userPassword], STOP_ON_FAILURE): Call Test Case 'Test Cases/PREGAME/SportBook/Login_Successfull' successfully

2018-12-24 13:17:23 - [TEST_CASE][PASSED] - Test Cases/PREGAME/SportBook/Login_Successfull: Test Cases/PREGAME/SportBook/Login_Successfull

2018-12-24 13:17:24 - [TEST_STEP][PASSED] - openBrowser(""): Browser is opened with url: ''

2018-12-24 13:17:24 - [MESSAGE][INFO] - Starting 'Chrome' driver

2018-12-24 13:17:24 - [MESSAGE][INFO] - Action delay is set to 0 seconds

2018-12-24 13:17:27 - [MESSAGE][PASSED] - Browser is opened with url: ''

2018-12-24 13:17:27 - [TEST_STEP][PASSED] - caps = getWebDriver().getCapabilities(): null

2018-12-24 13:17:27 - [TEST_STEP][PASSED] - plataform = caps.getPlatform(): null

2018-12-24 13:17:27 - [TEST_STEP][PASSED] - navigateToUrl(url): Navigate to 'http://pp-ids-pregame.bminc.eu/' successfully

2018-12-24 13:17:31 - [MESSAGE][PASSED] - Navigate to 'http://pp-ids-pregame.bminc.eu/' successfully

2018-12-24 13:17:31 - [TEST_STEP][PASSED] - if (!(plataform.equalsIgnoreCase("ANDROID"))): Current window maximized

2018-12-24 13:17:31 - [TEST_STEP][PASSED] - maximizeWindow(): Current window maximized

2018-12-24 13:17:32 - [MESSAGE][PASSED] - Current window maximized

2018-12-24 13:17:32 - [TEST_STEP][PASSED] - try: Object 'Object Repository/Repositorio Sportbook/Login/div_Logout' is visible

2018-12-24 13:17:32 - [TEST_STEP][PASSED] - delay(2): Delayed 2 second(s)

2018-12-24 13:17:34 - [MESSAGE][PASSED] - Delayed 2 second(s)

2018-12-24 13:17:34 - [TEST_STEP][PASSED] - waitForElementPresent(findTestObject("Repositorio Apuestas deportivas juegos/a_Ingresar"), 20): Object 'Object Repository/Repositorio Apuestas deportivas juegos/a_Ingresar' is present

2018-12-24 13:17:34 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Apuestas deportivas juegos/a_Ingresar' is present

2018-12-24 13:17:34 - [TEST_STEP][PASSED] - delay(2): Delayed 2 second(s)

2018-12-24 13:17:36 - [MESSAGE][PASSED] - Delayed 2 second(s)

2018-12-24 13:17:36 - [TEST_STEP][PASSED] - click(findTestObject("Repositorio Apuestas deportivas juegos/a_Ingresar")): Object: 'Object Repository/Repositorio Apuestas deportivas juegos/a_Ingresar' is clicked on

2018-12-24 13:17:36 - [MESSAGE][PASSED] - Object: 'Object Repository/Repositorio Apuestas deportivas juegos/a_Ingresar' is clicked on

2018-12-24 13:17:36 - [TEST_STEP][PASSED] - delay(2): Delayed 2 second(s)

2018-12-24 13:17:38 - [MESSAGE][PASSED] - Delayed 2 second(s)

2018-12-24 13:17:38 - [TEST_STEP][PASSED] - waitForElementVisible(findTestObject("Repositorio Apuestas deportivas juegos/input_Bienvenido_user"), 20): Object 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_user' is visible

2018-12-24 13:17:38 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_user' is visible

2018-12-24 13:17:38 - [TEST_STEP][PASSED] - sendKeys(findTestObject("Repositorio Apuestas deportivas juegos/input_Bienvenido_user"), loginUser): Keys '10075T' sent to object: 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_user'

2018-12-24 13:17:38 - [MESSAGE][PASSED] - Keys '10075T' sent to object: 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_user'

2018-12-24 13:17:38 - [TEST_STEP][PASSED] - sendKeys(findTestObject("Repositorio Apuestas deportivas juegos/input_Bienvenido_password"), loginPassword): Keys '1234' sent to object: 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_password'

2018-12-24 13:17:38 - [MESSAGE][PASSED] - Keys '1234' sent to object: 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_password'

2018-12-24 13:17:38 - [TEST_STEP][PASSED] - click(findTestObject("Repositorio Apuestas deportivas juegos/button_Entrar")): Object: 'Object Repository/Repositorio Apuestas deportivas juegos/button_Entrar' is clicked on

2018-12-24 13:17:42 - [MESSAGE][PASSED] - Object: 'Object Repository/Repositorio Apuestas deportivas juegos/button_Entrar' is clicked on

2018-12-24 13:17:42 - [TEST_STEP][PASSED] - waitForElementVisible(findTestObject("Repositorio Sportbook/li_PIN10075T"), 3): Object 'Object Repository/Repositorio Sportbook/li_PIN10075T' is visible

2018-12-24 13:17:42 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Sportbook/li_PIN10075T' is visible

2018-12-24 13:17:42 - [TEST_STEP][PASSED] - if (!(mobileBrowser)): Object 'Object Repository/Repositorio Sportbook/Login/div_Logout' is visible

2018-12-24 13:17:42 - [TEST_STEP][PASSED] - verifyElementVisible(findTestObject("Repositorio Sportbook/Login/div_Logout")): Object 'Object Repository/Repositorio Sportbook/Login/div_Logout' is visible

2018-12-24 13:17:42 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Sportbook/Login/div_Logout' is visible

2018-12-24 13:17:42 - [MESSAGE][PASSED] - Call Test Case 'Test Cases/PREGAME/SportBook/Login_Successfull' successfully

2018-12-24 13:17:42 - [TEST_STEP][PASSED] - usuarioLogeado: null

2018-12-24 13:17:42 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 8, mycompany.GetTestingConfig.getOperatingSystem()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:42 - [MESSAGE][PASSED] - mycompany.GetTestingConfig.getOperatingSystem is PASSED

2018-12-24 13:17:42 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:42 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 10, mycompany.GetTestingConfig.getScreenResolution()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - mycompany.GetTestingConfig.getScreenResolution is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 9, mycompany.GetTestingConfig.getBrowserAndVersion()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - mycompany.GetTestingConfig.getBrowserAndVersion is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - verifyElementVisible(findTestObject("Repositorio Sportbook/Permisos/Casino/div_Casino")): Object 'Object Repository/Repositorio Sportbook/Permisos/Casino/div_Casino' is visible

2018-12-24 13:17:43 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Sportbook/Permisos/Casino/div_Casino' is visible

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - permiso = getAttribute(findTestObject("Repositorio Sportbook/Permisos/Casino/div_Casino"), "textContent"): Attribute 'textContent' of object 'Object Repository/Repositorio Sportbook/Permisos/Casino/div_Casino' is: 'Casino'

2018-12-24 13:17:43 - [MESSAGE][PASSED] - Attribute 'textContent' of object 'Object Repository/Repositorio Sportbook/Permisos/Casino/div_Casino' is: 'Casino'

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 11, permiso): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 12, PASSED): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 13, "Permiso Casino es correctamente accesible para el usuario"): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:43 - [TEST_STEP][ERROR] - Finally: Finally FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosCasino.run(PermisosCasino:102)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545429055765.run(Script1545429055765.groovy:102)
	... 13 more


2018-12-24 13:17:43 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 7, com.utils.DateUtil.getHours()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.DateUtil.getHours is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 6, com.utils.DateUtil.getDate()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.DateUtil.getDate is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.closeFileInStream(): com.utils.ExcelsUtils.closeFileInStream is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.closeFileInStream is PASSED

2018-12-24 13:17:43 - [TEST_STEP][ERROR] - com.utils.ExcelsUtils.loadFileOutputStream(permisosExcelRuta): Finally FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosCasino.run(PermisosCasino:102)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545429055765.run(Script1545429055765.groovy:102)
	... 13 more


2018-12-24 13:17:43 - [MESSAGE][ERROR] - java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)

2018-12-24 13:17:43 - [MESSAGE][ERROR] - Finally FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosCasino.run(PermisosCasino:102)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545429055765.run(Script1545429055765.groovy:102)
	... 13 more]]></system-out>
         <system-err><![CDATA[2018-12-24 13:17:22 - [TEST_CASE][ERROR] - Test Cases/PREGAME/Permisos/PermisosCasino: Test Cases/PREGAME/Permisos/PermisosCasino FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosCasino.run(PermisosCasino:102)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545429055765.run(Script1545429055765.groovy:102)
	... 13 more]]></system-err>
      </testcase>
      <testcase name="Test Cases/PREGAME/Permisos/PermisosHorses" classname="Test Cases/PREGAME/Permisos/PermisosHorses" status="ERROR">
         <error type="ERROR" message="Test Cases/PREGAME/Permisos/PermisosHorses FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosHorses.run(PermisosHorses:106)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545406466189.run(Script1545406466189.groovy:106)
	... 13 more
"/>
         <system-out><![CDATA[2018-12-24 13:17:43 - [TEST_CASE][ERROR] - Test Cases/PREGAME/Permisos/PermisosHorses: Test Cases/PREGAME/Permisos/PermisosHorses FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosHorses.run(PermisosHorses:106)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545406466189.run(Script1545406466189.groovy:106)
	... 13 more


2018-12-24 13:17:43 - [TEST_STEP][PASSED] - log = new com.kms.katalon.core.logging.KeywordLogger(): null

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.loadFileInputStream(permisosExcelRuta): com.utils.ExcelsUtils.loadFileInputStream is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.loadFileInputStream is PASSED

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.createReadXSSFWorkbook(): com.utils.ExcelsUtils.createReadXSSFWorkbook is PASSED

2018-12-24 13:17:43 - [MESSAGE][INFO] - input file create  Read java.io.FileInputStream@4422dd48

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.createReadXSSFWorkbook is PASSED

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.loadXSSFSheet("Horses"): com.utils.ExcelsUtils.loadXSSFSheet is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.loadXSSFSheet is PASSED

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - url = com.utils.ExcelsUtils.getColumValue(1, 1): com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - userName = com.utils.ExcelsUtils.getColumValue(1, 2): com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - userPassword = com.utils.ExcelsUtils.getColumValue(1, 3): com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - startHour = com.utils.DateUtil.getHours(): com.utils.DateUtil.getHours is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.DateUtil.getHours is PASSED

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 4, com.utils.DateUtil.getDate()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.DateUtil.getDate is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 5, startHour): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:43 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - try: com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - if (!(usuarioLogeado)): null

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - callTestCase(findTestCase("PREGAME/SportBook/Login_Successfull"), ["url":url, "loginUser":userName, "loginPassword":userPassword], STOP_ON_FAILURE): Call Test Case 'Test Cases/PREGAME/SportBook/Login_Successfull' successfully

2018-12-24 13:17:43 - [TEST_CASE][PASSED] - Test Cases/PREGAME/SportBook/Login_Successfull: Test Cases/PREGAME/SportBook/Login_Successfull

2018-12-24 13:17:43 - [TEST_STEP][PASSED] - openBrowser(""): Browser is opened with url: ''

2018-12-24 13:17:43 - [MESSAGE][WARNING] - A browser is already opened. Closing browser and opening a new one

2018-12-24 13:17:44 - [MESSAGE][INFO] - Starting 'Chrome' driver

2018-12-24 13:17:47 - [MESSAGE][PASSED] - Browser is opened with url: ''

2018-12-24 13:17:47 - [TEST_STEP][PASSED] - caps = getWebDriver().getCapabilities(): null

2018-12-24 13:17:47 - [TEST_STEP][PASSED] - plataform = caps.getPlatform(): null

2018-12-24 13:17:47 - [TEST_STEP][PASSED] - navigateToUrl(url): Navigate to 'http://pp-ids-pregame.bminc.eu/' successfully

2018-12-24 13:17:49 - [MESSAGE][PASSED] - Navigate to 'http://pp-ids-pregame.bminc.eu/' successfully

2018-12-24 13:17:49 - [TEST_STEP][PASSED] - if (!(plataform.equalsIgnoreCase("ANDROID"))): Current window maximized

2018-12-24 13:17:49 - [TEST_STEP][PASSED] - maximizeWindow(): Current window maximized

2018-12-24 13:17:51 - [MESSAGE][PASSED] - Current window maximized

2018-12-24 13:17:51 - [TEST_STEP][PASSED] - try: Object 'Object Repository/Repositorio Sportbook/Login/div_Logout' is visible

2018-12-24 13:17:51 - [TEST_STEP][PASSED] - delay(2): Delayed 2 second(s)

2018-12-24 13:17:53 - [MESSAGE][PASSED] - Delayed 2 second(s)

2018-12-24 13:17:53 - [TEST_STEP][PASSED] - waitForElementPresent(findTestObject("Repositorio Apuestas deportivas juegos/a_Ingresar"), 20): Object 'Object Repository/Repositorio Apuestas deportivas juegos/a_Ingresar' is present

2018-12-24 13:17:53 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Apuestas deportivas juegos/a_Ingresar' is present

2018-12-24 13:17:53 - [TEST_STEP][PASSED] - delay(2): Delayed 2 second(s)

2018-12-24 13:17:55 - [MESSAGE][PASSED] - Delayed 2 second(s)

2018-12-24 13:17:55 - [TEST_STEP][PASSED] - click(findTestObject("Repositorio Apuestas deportivas juegos/a_Ingresar")): Object: 'Object Repository/Repositorio Apuestas deportivas juegos/a_Ingresar' is clicked on

2018-12-24 13:17:55 - [MESSAGE][PASSED] - Object: 'Object Repository/Repositorio Apuestas deportivas juegos/a_Ingresar' is clicked on

2018-12-24 13:17:55 - [TEST_STEP][PASSED] - delay(2): Delayed 2 second(s)

2018-12-24 13:17:57 - [MESSAGE][PASSED] - Delayed 2 second(s)

2018-12-24 13:17:57 - [TEST_STEP][PASSED] - waitForElementVisible(findTestObject("Repositorio Apuestas deportivas juegos/input_Bienvenido_user"), 20): Object 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_user' is visible

2018-12-24 13:17:57 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_user' is visible

2018-12-24 13:17:57 - [TEST_STEP][PASSED] - sendKeys(findTestObject("Repositorio Apuestas deportivas juegos/input_Bienvenido_user"), loginUser): Keys '10075T' sent to object: 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_user'

2018-12-24 13:17:57 - [MESSAGE][PASSED] - Keys '10075T' sent to object: 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_user'

2018-12-24 13:17:57 - [TEST_STEP][PASSED] - sendKeys(findTestObject("Repositorio Apuestas deportivas juegos/input_Bienvenido_password"), loginPassword): Keys '1234' sent to object: 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_password'

2018-12-24 13:17:57 - [MESSAGE][PASSED] - Keys '1234' sent to object: 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_password'

2018-12-24 13:17:57 - [TEST_STEP][PASSED] - click(findTestObject("Repositorio Apuestas deportivas juegos/button_Entrar")): Object: 'Object Repository/Repositorio Apuestas deportivas juegos/button_Entrar' is clicked on

2018-12-24 13:17:59 - [MESSAGE][PASSED] - Object: 'Object Repository/Repositorio Apuestas deportivas juegos/button_Entrar' is clicked on

2018-12-24 13:17:59 - [TEST_STEP][PASSED] - waitForElementVisible(findTestObject("Repositorio Sportbook/li_PIN10075T"), 3): Object 'Object Repository/Repositorio Sportbook/li_PIN10075T' is visible

2018-12-24 13:18:00 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Sportbook/li_PIN10075T' is visible

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - if (!(mobileBrowser)): Object 'Object Repository/Repositorio Sportbook/Login/div_Logout' is visible

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - verifyElementVisible(findTestObject("Repositorio Sportbook/Login/div_Logout")): Object 'Object Repository/Repositorio Sportbook/Login/div_Logout' is visible

2018-12-24 13:18:00 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Sportbook/Login/div_Logout' is visible

2018-12-24 13:18:00 - [MESSAGE][PASSED] - Call Test Case 'Test Cases/PREGAME/SportBook/Login_Successfull' successfully

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - usuarioLogeado: null

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 8, mycompany.GetTestingConfig.getOperatingSystem()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - mycompany.GetTestingConfig.getOperatingSystem is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 10, mycompany.GetTestingConfig.getScreenResolution()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - mycompany.GetTestingConfig.getScreenResolution is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 9, mycompany.GetTestingConfig.getBrowserAndVersion()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - mycompany.GetTestingConfig.getBrowserAndVersion is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - verifyElementVisible(findTestObject("Repositorio Sportbook/Permisos/Horses/div_Caballos")): Object 'Object Repository/Repositorio Sportbook/Permisos/Horses/div_Caballos' is visible

2018-12-24 13:18:00 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Sportbook/Permisos/Horses/div_Caballos' is visible

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - permiso = getAttribute(findTestObject("Repositorio Sportbook/Permisos/Horses/div_Caballos"), "textContent"): Attribute 'textContent' of object 'Object Repository/Repositorio Sportbook/Permisos/Horses/div_Caballos' is: 'Horses'

2018-12-24 13:18:00 - [MESSAGE][PASSED] - Attribute 'textContent' of object 'Object Repository/Repositorio Sportbook/Permisos/Horses/div_Caballos' is: 'Horses'

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 11, permiso): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 7, com.utils.DateUtil.getHours()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.DateUtil.getHours is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 6, com.utils.DateUtil.getDate()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.DateUtil.getDate is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 12, PASSED): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 13, "Permiso Horses es correctamente accesible para el usuario"): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [TEST_STEP][ERROR] - Finally: Finally FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosHorses.run(PermisosHorses:106)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545406466189.run(Script1545406466189.groovy:106)
	... 13 more


2018-12-24 13:18:00 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 7, com.utils.DateUtil.getHours()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.DateUtil.getHours is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 6, com.utils.DateUtil.getDate()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.DateUtil.getDate is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.closeFileInStream(): com.utils.ExcelsUtils.closeFileInStream is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.closeFileInStream is PASSED

2018-12-24 13:18:00 - [TEST_STEP][ERROR] - com.utils.ExcelsUtils.loadFileOutputStream(permisosExcelRuta): Finally FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosHorses.run(PermisosHorses:106)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545406466189.run(Script1545406466189.groovy:106)
	... 13 more


2018-12-24 13:18:00 - [MESSAGE][ERROR] - java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)

2018-12-24 13:18:00 - [MESSAGE][ERROR] - Finally FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosHorses.run(PermisosHorses:106)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545406466189.run(Script1545406466189.groovy:106)
	... 13 more]]></system-out>
         <system-err><![CDATA[2018-12-24 13:17:43 - [TEST_CASE][ERROR] - Test Cases/PREGAME/Permisos/PermisosHorses: Test Cases/PREGAME/Permisos/PermisosHorses FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosHorses.run(PermisosHorses:106)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545406466189.run(Script1545406466189.groovy:106)
	... 13 more]]></system-err>
      </testcase>
      <testcase name="Test Cases/PREGAME/Permisos/PermisosLive" classname="Test Cases/PREGAME/Permisos/PermisosLive" status="ERROR">
         <error type="ERROR" message="Test Cases/PREGAME/Permisos/PermisosLive FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosLive.run(PermisosLive:103)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545344237721.run(Script1545344237721.groovy:103)
	... 13 more
"/>
         <system-out><![CDATA[2018-12-24 13:18:00 - [TEST_CASE][ERROR] - Test Cases/PREGAME/Permisos/PermisosLive: Test Cases/PREGAME/Permisos/PermisosLive FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosLive.run(PermisosLive:103)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545344237721.run(Script1545344237721.groovy:103)
	... 13 more


2018-12-24 13:18:00 - [TEST_STEP][PASSED] - log = new com.kms.katalon.core.logging.KeywordLogger(): null

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.loadFileInputStream(permisosExcelRuta): com.utils.ExcelsUtils.loadFileInputStream is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.loadFileInputStream is PASSED

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.createReadXSSFWorkbook(): com.utils.ExcelsUtils.createReadXSSFWorkbook is PASSED

2018-12-24 13:18:00 - [MESSAGE][INFO] - input file create  Read java.io.FileInputStream@a18649a

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.createReadXSSFWorkbook is PASSED

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.loadXSSFSheet("Live"): com.utils.ExcelsUtils.loadXSSFSheet is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.loadXSSFSheet is PASSED

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - url = com.utils.ExcelsUtils.getColumValue(1, 1): com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - userName = com.utils.ExcelsUtils.getColumValue(1, 2): com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - userPassword = com.utils.ExcelsUtils.getColumValue(1, 3): com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - startHour = com.utils.DateUtil.getHours(): com.utils.DateUtil.getHours is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.DateUtil.getHours is PASSED

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 4, com.utils.DateUtil.getDate()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.DateUtil.getDate is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 5, startHour): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - try: com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - if (!(usuarioLogeado)): null

2018-12-24 13:18:00 - [TEST_STEP][PASSED] - callTestCase(findTestCase("PREGAME/SportBook/Login_Successfull"), ["url":url, "loginUser":userName, "loginPassword":userPassword], STOP_ON_FAILURE): Call Test Case 'Test Cases/PREGAME/SportBook/Login_Successfull' successfully

2018-12-24 13:18:01 - [TEST_CASE][PASSED] - Test Cases/PREGAME/SportBook/Login_Successfull: Test Cases/PREGAME/SportBook/Login_Successfull

2018-12-24 13:18:01 - [TEST_STEP][PASSED] - openBrowser(""): Browser is opened with url: ''

2018-12-24 13:18:01 - [MESSAGE][WARNING] - A browser is already opened. Closing browser and opening a new one

2018-12-24 13:18:01 - [MESSAGE][INFO] - Starting 'Chrome' driver

2018-12-24 13:18:04 - [MESSAGE][PASSED] - Browser is opened with url: ''

2018-12-24 13:18:04 - [TEST_STEP][PASSED] - caps = getWebDriver().getCapabilities(): null

2018-12-24 13:18:04 - [TEST_STEP][PASSED] - plataform = caps.getPlatform(): null

2018-12-24 13:18:04 - [TEST_STEP][PASSED] - navigateToUrl(url): Navigate to 'http://pp-ids-pregame.bminc.eu/' successfully

2018-12-24 13:18:07 - [MESSAGE][PASSED] - Navigate to 'http://pp-ids-pregame.bminc.eu/' successfully

2018-12-24 13:18:07 - [TEST_STEP][PASSED] - if (!(plataform.equalsIgnoreCase("ANDROID"))): Current window maximized

2018-12-24 13:18:07 - [TEST_STEP][PASSED] - maximizeWindow(): Current window maximized

2018-12-24 13:18:08 - [MESSAGE][PASSED] - Current window maximized

2018-12-24 13:18:08 - [TEST_STEP][PASSED] - try: Object 'Object Repository/Repositorio Sportbook/Login/div_Logout' is visible

2018-12-24 13:18:08 - [TEST_STEP][PASSED] - delay(2): Delayed 2 second(s)

2018-12-24 13:18:10 - [MESSAGE][PASSED] - Delayed 2 second(s)

2018-12-24 13:18:10 - [TEST_STEP][PASSED] - waitForElementPresent(findTestObject("Repositorio Apuestas deportivas juegos/a_Ingresar"), 20): Object 'Object Repository/Repositorio Apuestas deportivas juegos/a_Ingresar' is present

2018-12-24 13:18:10 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Apuestas deportivas juegos/a_Ingresar' is present

2018-12-24 13:18:10 - [TEST_STEP][PASSED] - delay(2): Delayed 2 second(s)

2018-12-24 13:18:12 - [MESSAGE][PASSED] - Delayed 2 second(s)

2018-12-24 13:18:12 - [TEST_STEP][PASSED] - click(findTestObject("Repositorio Apuestas deportivas juegos/a_Ingresar")): Object: 'Object Repository/Repositorio Apuestas deportivas juegos/a_Ingresar' is clicked on

2018-12-24 13:18:12 - [MESSAGE][PASSED] - Object: 'Object Repository/Repositorio Apuestas deportivas juegos/a_Ingresar' is clicked on

2018-12-24 13:18:12 - [TEST_STEP][PASSED] - delay(2): Delayed 2 second(s)

2018-12-24 13:18:14 - [MESSAGE][PASSED] - Delayed 2 second(s)

2018-12-24 13:18:14 - [TEST_STEP][PASSED] - waitForElementVisible(findTestObject("Repositorio Apuestas deportivas juegos/input_Bienvenido_user"), 20): Object 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_user' is visible

2018-12-24 13:18:14 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_user' is visible

2018-12-24 13:18:14 - [TEST_STEP][PASSED] - sendKeys(findTestObject("Repositorio Apuestas deportivas juegos/input_Bienvenido_user"), loginUser): Keys '10075T' sent to object: 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_user'

2018-12-24 13:18:15 - [MESSAGE][PASSED] - Keys '10075T' sent to object: 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_user'

2018-12-24 13:18:15 - [TEST_STEP][PASSED] - sendKeys(findTestObject("Repositorio Apuestas deportivas juegos/input_Bienvenido_password"), loginPassword): Keys '1234' sent to object: 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_password'

2018-12-24 13:18:15 - [MESSAGE][PASSED] - Keys '1234' sent to object: 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_password'

2018-12-24 13:18:15 - [TEST_STEP][PASSED] - click(findTestObject("Repositorio Apuestas deportivas juegos/button_Entrar")): Object: 'Object Repository/Repositorio Apuestas deportivas juegos/button_Entrar' is clicked on

2018-12-24 13:18:17 - [MESSAGE][PASSED] - Object: 'Object Repository/Repositorio Apuestas deportivas juegos/button_Entrar' is clicked on

2018-12-24 13:18:17 - [TEST_STEP][PASSED] - waitForElementVisible(findTestObject("Repositorio Sportbook/li_PIN10075T"), 3): Object 'Object Repository/Repositorio Sportbook/li_PIN10075T' is visible

2018-12-24 13:18:17 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Sportbook/li_PIN10075T' is visible

2018-12-24 13:18:17 - [TEST_STEP][PASSED] - if (!(mobileBrowser)): Object 'Object Repository/Repositorio Sportbook/Login/div_Logout' is visible

2018-12-24 13:18:17 - [TEST_STEP][PASSED] - verifyElementVisible(findTestObject("Repositorio Sportbook/Login/div_Logout")): Object 'Object Repository/Repositorio Sportbook/Login/div_Logout' is visible

2018-12-24 13:18:17 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Sportbook/Login/div_Logout' is visible

2018-12-24 13:18:17 - [MESSAGE][PASSED] - Call Test Case 'Test Cases/PREGAME/SportBook/Login_Successfull' successfully

2018-12-24 13:18:17 - [TEST_STEP][PASSED] - usuarioLogeado: null

2018-12-24 13:18:17 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 8, mycompany.GetTestingConfig.getOperatingSystem()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [MESSAGE][PASSED] - mycompany.GetTestingConfig.getOperatingSystem is PASSED

2018-12-24 13:18:17 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 10, mycompany.GetTestingConfig.getScreenResolution()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [MESSAGE][PASSED] - mycompany.GetTestingConfig.getScreenResolution is PASSED

2018-12-24 13:18:17 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 9, mycompany.GetTestingConfig.getBrowserAndVersion()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [MESSAGE][PASSED] - mycompany.GetTestingConfig.getBrowserAndVersion is PASSED

2018-12-24 13:18:17 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [TEST_STEP][PASSED] - verifyElementVisible(findTestObject("Repositorio Sportbook/Permisos/Live/div_En Vivo")): Object 'Object Repository/Repositorio Sportbook/Permisos/Live/div_En Vivo' is visible

2018-12-24 13:18:17 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Sportbook/Permisos/Live/div_En Vivo' is visible

2018-12-24 13:18:17 - [TEST_STEP][PASSED] - permiso = getAttribute(findTestObject("Repositorio Sportbook/Permisos/Live/div_En Vivo"), "textContent"): Attribute 'textContent' of object 'Object Repository/Repositorio Sportbook/Permisos/Live/div_En Vivo' is: 'Live'

2018-12-24 13:18:17 - [MESSAGE][PASSED] - Attribute 'textContent' of object 'Object Repository/Repositorio Sportbook/Permisos/Live/div_En Vivo' is: 'Live'

2018-12-24 13:18:17 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 11, permiso): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 7, com.utils.DateUtil.getHours()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [MESSAGE][PASSED] - com.utils.DateUtil.getHours is PASSED

2018-12-24 13:18:17 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 6, com.utils.DateUtil.getDate()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [MESSAGE][PASSED] - com.utils.DateUtil.getDate is PASSED

2018-12-24 13:18:17 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 12, PASSED): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 13, "Permiso Live es correctamente accesible para el usuario"): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [TEST_STEP][ERROR] - Finally: Finally FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosLive.run(PermisosLive:103)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545344237721.run(Script1545344237721.groovy:103)
	... 13 more


2018-12-24 13:18:17 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 7, com.utils.DateUtil.getHours()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [MESSAGE][PASSED] - com.utils.DateUtil.getHours is PASSED

2018-12-24 13:18:17 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 6, com.utils.DateUtil.getDate()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [MESSAGE][PASSED] - com.utils.DateUtil.getDate is PASSED

2018-12-24 13:18:17 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:17 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.closeFileInStream(): com.utils.ExcelsUtils.closeFileInStream is PASSED

2018-12-24 13:18:17 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.closeFileInStream is PASSED

2018-12-24 13:18:17 - [TEST_STEP][ERROR] - com.utils.ExcelsUtils.loadFileOutputStream(permisosExcelRuta): Finally FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosLive.run(PermisosLive:103)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545344237721.run(Script1545344237721.groovy:103)
	... 13 more


2018-12-24 13:18:17 - [MESSAGE][ERROR] - java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)

2018-12-24 13:18:17 - [MESSAGE][ERROR] - Finally FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosLive.run(PermisosLive:103)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545344237721.run(Script1545344237721.groovy:103)
	... 13 more]]></system-out>
         <system-err><![CDATA[2018-12-24 13:18:00 - [TEST_CASE][ERROR] - Test Cases/PREGAME/Permisos/PermisosLive: Test Cases/PREGAME/Permisos/PermisosLive FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosLive.run(PermisosLive:103)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545344237721.run(Script1545344237721.groovy:103)
	... 13 more]]></system-err>
      </testcase>
      <testcase name="Test Cases/PREGAME/Permisos/PermisoSportBook" classname="Test Cases/PREGAME/Permisos/PermisoSportBook" status="ERROR">
         <error type="ERROR" message="Test Cases/PREGAME/Permisos/PermisoSportBook FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisoSportBook.run(PermisoSportBook:88)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545255535077.run(Script1545255535077.groovy:88)
	... 13 more
"/>
         <system-out><![CDATA[2018-12-24 13:18:17 - [TEST_CASE][ERROR] - Test Cases/PREGAME/Permisos/PermisoSportBook: Test Cases/PREGAME/Permisos/PermisoSportBook FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisoSportBook.run(PermisoSportBook:88)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545255535077.run(Script1545255535077.groovy:88)
	... 13 more


2018-12-24 13:18:18 - [TEST_STEP][PASSED] - log = new com.kms.katalon.core.logging.KeywordLogger(): null

2018-12-24 13:18:18 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.loadFileInputStream(permisosExcelRuta): com.utils.ExcelsUtils.loadFileInputStream is PASSED

2018-12-24 13:18:18 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.loadFileInputStream is PASSED

2018-12-24 13:18:18 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.createReadXSSFWorkbook(): com.utils.ExcelsUtils.createReadXSSFWorkbook is PASSED

2018-12-24 13:18:18 - [MESSAGE][INFO] - input file create  Read java.io.FileInputStream@6ff6efdc

2018-12-24 13:18:18 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.createReadXSSFWorkbook is PASSED

2018-12-24 13:18:18 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.loadXSSFSheet("Sportbook"): com.utils.ExcelsUtils.loadXSSFSheet is PASSED

2018-12-24 13:18:18 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.loadXSSFSheet is PASSED

2018-12-24 13:18:18 - [TEST_STEP][PASSED] - url = com.utils.ExcelsUtils.getColumValue(1, 1): com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:18:18 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:18:18 - [TEST_STEP][PASSED] - userName = com.utils.ExcelsUtils.getColumValue(1, 2): com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:18:18 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:18:18 - [TEST_STEP][PASSED] - userPassword = com.utils.ExcelsUtils.getColumValue(1, 3): com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:18:18 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.getColumValue is PASSED

2018-12-24 13:18:18 - [TEST_STEP][PASSED] - startHour = com.utils.DateUtil.getHours(): com.utils.DateUtil.getHours is PASSED

2018-12-24 13:18:18 - [MESSAGE][PASSED] - com.utils.DateUtil.getHours is PASSED

2018-12-24 13:18:18 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 4, com.utils.DateUtil.getDate()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:18 - [MESSAGE][PASSED] - com.utils.DateUtil.getDate is PASSED

2018-12-24 13:18:18 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:18 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 5, startHour): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:18 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:18 - [TEST_STEP][PASSED] - try: com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:18 - [TEST_STEP][PASSED] - if (!(usuarioLogeado)): null

2018-12-24 13:18:18 - [TEST_STEP][PASSED] - callTestCase(findTestCase("PREGAME/SportBook/Login_Successfull"), ["url":url, "loginUser":userName, "loginPassword":userPassword], STOP_ON_FAILURE): Call Test Case 'Test Cases/PREGAME/SportBook/Login_Successfull' successfully

2018-12-24 13:18:18 - [TEST_CASE][PASSED] - Test Cases/PREGAME/SportBook/Login_Successfull: Test Cases/PREGAME/SportBook/Login_Successfull

2018-12-24 13:18:18 - [TEST_STEP][PASSED] - openBrowser(""): Browser is opened with url: ''

2018-12-24 13:18:18 - [MESSAGE][WARNING] - A browser is already opened. Closing browser and opening a new one

2018-12-24 13:18:18 - [MESSAGE][INFO] - Starting 'Chrome' driver

2018-12-24 13:18:21 - [MESSAGE][PASSED] - Browser is opened with url: ''

2018-12-24 13:18:21 - [TEST_STEP][PASSED] - caps = getWebDriver().getCapabilities(): null

2018-12-24 13:18:21 - [TEST_STEP][PASSED] - plataform = caps.getPlatform(): null

2018-12-24 13:18:21 - [TEST_STEP][PASSED] - navigateToUrl(url): Navigate to 'http://pp-ids-pregame.bminc.eu/' successfully

2018-12-24 13:18:25 - [MESSAGE][PASSED] - Navigate to 'http://pp-ids-pregame.bminc.eu/' successfully

2018-12-24 13:18:25 - [TEST_STEP][PASSED] - if (!(plataform.equalsIgnoreCase("ANDROID"))): Current window maximized

2018-12-24 13:18:25 - [TEST_STEP][PASSED] - maximizeWindow(): Current window maximized

2018-12-24 13:18:26 - [MESSAGE][PASSED] - Current window maximized

2018-12-24 13:18:26 - [TEST_STEP][PASSED] - try: Object 'Object Repository/Repositorio Sportbook/Login/div_Logout' is visible

2018-12-24 13:18:26 - [TEST_STEP][PASSED] - delay(2): Delayed 2 second(s)

2018-12-24 13:18:28 - [MESSAGE][PASSED] - Delayed 2 second(s)

2018-12-24 13:18:28 - [TEST_STEP][PASSED] - waitForElementPresent(findTestObject("Repositorio Apuestas deportivas juegos/a_Ingresar"), 20): Object 'Object Repository/Repositorio Apuestas deportivas juegos/a_Ingresar' is present

2018-12-24 13:18:28 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Apuestas deportivas juegos/a_Ingresar' is present

2018-12-24 13:18:28 - [TEST_STEP][PASSED] - delay(2): Delayed 2 second(s)

2018-12-24 13:18:30 - [MESSAGE][PASSED] - Delayed 2 second(s)

2018-12-24 13:18:30 - [TEST_STEP][PASSED] - click(findTestObject("Repositorio Apuestas deportivas juegos/a_Ingresar")): Object: 'Object Repository/Repositorio Apuestas deportivas juegos/a_Ingresar' is clicked on

2018-12-24 13:18:30 - [MESSAGE][PASSED] - Object: 'Object Repository/Repositorio Apuestas deportivas juegos/a_Ingresar' is clicked on

2018-12-24 13:18:30 - [TEST_STEP][PASSED] - delay(2): Delayed 2 second(s)

2018-12-24 13:18:32 - [MESSAGE][PASSED] - Delayed 2 second(s)

2018-12-24 13:18:32 - [TEST_STEP][PASSED] - waitForElementVisible(findTestObject("Repositorio Apuestas deportivas juegos/input_Bienvenido_user"), 20): Object 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_user' is visible

2018-12-24 13:18:32 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_user' is visible

2018-12-24 13:18:32 - [TEST_STEP][PASSED] - sendKeys(findTestObject("Repositorio Apuestas deportivas juegos/input_Bienvenido_user"), loginUser): Keys '10075T' sent to object: 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_user'

2018-12-24 13:18:32 - [MESSAGE][PASSED] - Keys '10075T' sent to object: 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_user'

2018-12-24 13:18:32 - [TEST_STEP][PASSED] - sendKeys(findTestObject("Repositorio Apuestas deportivas juegos/input_Bienvenido_password"), loginPassword): Keys '1234' sent to object: 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_password'

2018-12-24 13:18:32 - [MESSAGE][PASSED] - Keys '1234' sent to object: 'Object Repository/Repositorio Apuestas deportivas juegos/input_Bienvenido_password'

2018-12-24 13:18:32 - [TEST_STEP][PASSED] - click(findTestObject("Repositorio Apuestas deportivas juegos/button_Entrar")): Object: 'Object Repository/Repositorio Apuestas deportivas juegos/button_Entrar' is clicked on

2018-12-24 13:18:36 - [MESSAGE][PASSED] - Object: 'Object Repository/Repositorio Apuestas deportivas juegos/button_Entrar' is clicked on

2018-12-24 13:18:36 - [TEST_STEP][PASSED] - waitForElementVisible(findTestObject("Repositorio Sportbook/li_PIN10075T"), 3): Object 'Object Repository/Repositorio Sportbook/li_PIN10075T' is visible

2018-12-24 13:18:36 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Sportbook/li_PIN10075T' is visible

2018-12-24 13:18:36 - [TEST_STEP][PASSED] - if (!(mobileBrowser)): Object 'Object Repository/Repositorio Sportbook/Login/div_Logout' is visible

2018-12-24 13:18:36 - [TEST_STEP][PASSED] - verifyElementVisible(findTestObject("Repositorio Sportbook/Login/div_Logout")): Object 'Object Repository/Repositorio Sportbook/Login/div_Logout' is visible

2018-12-24 13:18:36 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Sportbook/Login/div_Logout' is visible

2018-12-24 13:18:36 - [MESSAGE][PASSED] - Call Test Case 'Test Cases/PREGAME/SportBook/Login_Successfull' successfully

2018-12-24 13:18:36 - [TEST_STEP][PASSED] - usuarioLogeado: null

2018-12-24 13:18:36 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 8, mycompany.GetTestingConfig.getOperatingSystem()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:36 - [MESSAGE][PASSED] - mycompany.GetTestingConfig.getOperatingSystem is PASSED

2018-12-24 13:18:36 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:36 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 10, mycompany.GetTestingConfig.getScreenResolution()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:36 - [MESSAGE][PASSED] - mycompany.GetTestingConfig.getScreenResolution is PASSED

2018-12-24 13:18:36 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:36 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 9, mycompany.GetTestingConfig.getBrowserAndVersion()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:36 - [MESSAGE][PASSED] - mycompany.GetTestingConfig.getBrowserAndVersion is PASSED

2018-12-24 13:18:36 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:36 - [TEST_STEP][PASSED] - verifyElementVisible(findTestObject("Repositorio Sportbook/Permisos/Sportbook/div_Sports")): Object 'Object Repository/Repositorio Sportbook/Permisos/Sportbook/div_Sports' is visible

2018-12-24 13:18:36 - [MESSAGE][PASSED] - Object 'Object Repository/Repositorio Sportbook/Permisos/Sportbook/div_Sports' is visible

2018-12-24 13:18:36 - [TEST_STEP][PASSED] - permiso = getAttribute(findTestObject("Repositorio Sportbook/Permisos/Sportbook/div_Sports"), "textContent"): Attribute 'textContent' of object 'Object Repository/Repositorio Sportbook/Permisos/Sportbook/div_Sports' is: 'Sports'

2018-12-24 13:18:36 - [MESSAGE][PASSED] - Attribute 'textContent' of object 'Object Repository/Repositorio Sportbook/Permisos/Sportbook/div_Sports' is: 'Sports'

2018-12-24 13:18:36 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 11, permiso): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:36 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:36 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 12, PASSED): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:36 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:36 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 13, "Permiso Sportbook es correctamente accesible para el usuario"): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:36 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:36 - [TEST_STEP][ERROR] - Finally: Finally FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisoSportBook.run(PermisoSportBook:88)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545255535077.run(Script1545255535077.groovy:88)
	... 13 more


2018-12-24 13:18:36 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 7, com.utils.DateUtil.getHours()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:36 - [MESSAGE][PASSED] - com.utils.DateUtil.getHours is PASSED

2018-12-24 13:18:36 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:36 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel(1, 6, com.utils.DateUtil.getDate()): com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:36 - [MESSAGE][PASSED] - com.utils.DateUtil.getDate is PASSED

2018-12-24 13:18:36 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.saveDataOnExcel is PASSED

2018-12-24 13:18:36 - [TEST_STEP][PASSED] - com.utils.ExcelsUtils.closeFileInStream(): com.utils.ExcelsUtils.closeFileInStream is PASSED

2018-12-24 13:18:36 - [MESSAGE][PASSED] - com.utils.ExcelsUtils.closeFileInStream is PASSED

2018-12-24 13:18:36 - [TEST_STEP][ERROR] - com.utils.ExcelsUtils.loadFileOutputStream(permisosExcelRuta): Finally FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisoSportBook.run(PermisoSportBook:88)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545255535077.run(Script1545255535077.groovy:88)
	... 13 more


2018-12-24 13:18:36 - [MESSAGE][ERROR] - java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)

2018-12-24 13:18:36 - [MESSAGE][ERROR] - Finally FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisoSportBook.run(PermisoSportBook:88)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545255535077.run(Script1545255535077.groovy:88)
	... 13 more]]></system-out>
         <system-err><![CDATA[2018-12-24 13:18:17 - [TEST_CASE][ERROR] - Test Cases/PREGAME/Permisos/PermisoSportBook: Test Cases/PREGAME/Permisos/PermisoSportBook FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisoSportBook.run(PermisoSportBook:88)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545255535077.run(Script1545255535077.groovy:88)
	... 13 more]]></system-err>
      </testcase>
      <system-out><![CDATA[2018-12-24 13:17:22 - [TEST_SUITE][ERROR] - TestSUitesPermisos: Test Cases/PREGAME/Permisos/PermisosCasino FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosCasino.run(PermisosCasino:102)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545429055765.run(Script1545429055765.groovy:102)
	... 13 more]]></system-out>
      <system-err><![CDATA[2018-12-24 13:17:22 - [TEST_SUITE][ERROR] - TestSUitesPermisos: Test Cases/PREGAME/Permisos/PermisosCasino FAILED.
Reason:
org.codehaus.groovy.runtime.InvokerInvocationException: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at PermisosCasino.run(PermisosCasino:102)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:328)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:319)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:298)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:290)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:224)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:129)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:112)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:149)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1545679040310.run(TempTestSuite1545679040310.groovy:36)
Caused by: java.io.FileNotFoundException: C:\QAAutomatizacion\Proyectos\TestData\PermisosTestData.xlsx (The process cannot access the file because it is being used by another process)
	at com.utils.ExcelsUtils.loadFileOutputStream(ExcelsUtils.groovy:38)
	at com.utils.ExcelsUtils.invokeMethod(ExcelsUtils.groovy)
	at com.kms.katalon.core.main.CustomKeywordDelegatingMetaClass.invokeStaticMethod(CustomKeywordDelegatingMetaClass.java:49)
	at Script1545429055765.run(Script1545429055765.groovy:102)
	... 13 more]]></system-err>
   </testsuite>
</testsuites>
